services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: databasemeucasamento
      POSTGRES_USER: myuser
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local