checkout:
  handle: silas-nc
  redirect-url: https://seusite.com/obrigado
  webhook-url: https://apicasarfacil.silasesofia.com.br/api/webhooks/infinitepay

gateway:
  base-url: https://api.infinitepay.io
  checkout-path: /invoices/public/checkout/links